### ISSUE TITLE
"cabal install" failed

### ISSUE THREAD

**Issue by luckypoem** [chrisdone/chrisdone-homepage#2]
hi.

root@AR:/usr/local/chrisdone-homepage# cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: chrisdone-homepage-0.1.0.0 (user goal)
trying: time-1.6.0.1/installed-1.6... (dependency of
chrisdone-homepage-0.1.0.0)
next goal: hakyll (dependency of chrisdone-homepage-0.1.0.0)
rejecting: hakyll-4.8.3.2, hakyll-4.8.3.1, hakyll-4.8.3.0, hakyll-4.8.2.0,
hakyll-4.8.1.0, hakyll-4.8.0.1, hakyll-4.8.0.0, hakyll-4.7.5.2,
hakyll-4.7.5.1, hakyll-4.7.5.0, hakyll-4.7.4.0, hakyll-4.7.3.1,
hakyll-4.7.3.0, hakyll-4.7.2.3, hakyll-4.7.2.2, hakyll-4.7.2.1,
hakyll-4.7.2.0, hakyll-4.7.1.0, hakyll-4.7.0.0, hakyll-4.6.9.0,
hakyll-4.6.8.1, hakyll-4.6.8.0, hakyll-4.6.7.1, hakyll-4.6.7.0,
hakyll-4.6.6.0, hakyll-4.6.5.0, hakyll-4.6.4.0, hakyll-4.6.3.0,
hakyll-4.6.2.0, hakyll-4.6.1.1, hakyll-4.6.1.0, hakyll-4.6.0.0,
hakyll-4.5.5.1, hakyll-4.5.5.0, hakyll-4.5.4.0, hakyll-4.5.3.0,
hakyll-4.5.2.0, hakyll-4.5.1.0, hakyll-4.5.0.2, hakyll-4.5.0.1,
hakyll-4.5.0.0, hakyll-4.4.3.2, hakyll-4.4.3.1, hakyll-4.4.3.0,
hakyll-4.4.2.0, hakyll-4.4.1.2, hakyll-4.4.1.1, hakyll-4.4.1.0,
hakyll-4.4.0.0, hakyll-4.3.3.0, hakyll-4.3.2.0, hakyll-4.3.1.0,
hakyll-4.3.0.0, hakyll-4.2.2.0, hakyll-4.2.1.2, hakyll-4.2.1.1,
hakyll-4.2.1.0, hakyll-4.2.0.0, hakyll-4.1.4.0, hakyll-4.1.3.0,
hakyll-4.1.2.1, hakyll-4.1.2.0, hakyll-4.1.1.0, hakyll-4.1.0.0,
hakyll-4.0.0.0, hakyll-3.5.3.0, hakyll-3.5.2.1 (conflict: chrisdone-homepage
=> hakyll==3.5.2.0)
rejecting: hakyll-3.5.2.0 (conflict: time==1.6.0.1/installed-1.6..., hakyll =>
time>=1.1 && <1.5)
rejecting: hakyll-3.5.1.0, hakyll-3.5.0.0, hakyll-3.4.2.1, hakyll-3.4.2.0,
hakyll-3.4.1.0, hakyll-3.4.0.0, hakyll-3.3.0.1, hakyll-3.3.0.0,
hakyll-3.2.8.1, hakyll-3.2.8.0, hakyll-3.2.7.2, hakyll-3.2.7.1,
hakyll-3.2.7.0, hakyll-3.2.6.2, hakyll-3.2.6.1, hakyll-3.2.6.0,
hakyll-3.2.5.1, hakyll-3.2.5.0, hakyll-3.2.4.2, hakyll-3.2.4.1,
hakyll-3.2.4.0, hakyll-3.2.3.2, hakyll-3.2.3.1, hakyll-3.2.3.0,
hakyll-3.2.2.0, hakyll-3.2.1.0, hakyll-3.2.0.10, hakyll-3.2.0.9,
hakyll-3.2.0.8, hakyll-3.2.0.7, hakyll-3.2.0.6, hakyll-3.2.0.5,
hakyll-3.2.0.4, hakyll-3.2.0.3, hakyll-3.2.0.2, hakyll-3.2.0.1,
hakyll-3.2.0.0, hakyll-3.1.2.8, hakyll-3.1.2.7, hakyll-3.1.2.6,
hakyll-3.1.2.5, hakyll-3.1.2.4, hakyll-3.1.2.3, hakyll-3.1.2.2,
hakyll-3.1.2.1, hakyll-3.1.2.0, hakyll-3.1.1.2, hakyll-3.1.1.1,
hakyll-3.1.1.0, hakyll-3.1.0.0, hakyll-3.0.2.2, hakyll-3.0.2.1,
hakyll-3.0.2.0, hakyll-3.0.1.4, hakyll-3.0.1.3, hakyll-3.0.1.2,
hakyll-3.0.1.1, hakyll-3.0.1.0, hakyll-3.0.0.4, hakyll-3.0.0.3,
hakyll-3.0.0.2, hakyll-2.4.4, hakyll-2.4.3, hakyll-2.4.2, hakyll-2.4.1,
hakyll-2.4, hakyll-2.3.1, hakyll-2.3, hakyll-2.2.2, hakyll-2.2.1, hakyll-2.2,
hakyll-2.1.1, hakyll-2.1, hakyll-2.0, hakyll-1.4, hakyll-1.3, hakyll-1.2,
hakyll-1.1, hakyll-1.0.1, hakyll-1.0, hakyll-0.4.1, hakyll-0.4, hakyll-0.3.2,
hakyll-0.3.1, hakyll-0.3, hakyll-0.2, hakyll-0.1 (conflict: chrisdone-homepage
=> hakyll==3.5.2.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
root@AR:/usr/local/chrisdone-homepage#

the version of hakyll installed with "stack install hakyll" is 4.8.3.2; so how to install  hakyll==3.5.2.0?

**Comment by chrisdone** [comment]
Yeah, I'm unable to build this anymore.
